# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - laravel-hr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_1ef171b92d084cae9e5b8f287dca5aa5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3ae3a7c9ad3b49668f5b3abb421342ec }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1ef171b92d084cae9e5b8f287dca5aa5 }}/laravel-webhooks:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'laravel-hr'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e80c662761fb48e6945d00e279dbc4c1 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1ef171b92d084cae9e5b8f287dca5aa5 }}/laravel-webhooks:${{ github.sha }}'